### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by rosegabe** [powerseb/NoPhish#5]
Great tool!

One minor issue:

When a user presses the CRTL + U key combination, for example, the noVNC session opens the source code of the website and there is no way to return to the HTML page of the website.

**Comment by powerseb** [comment]
Many thanks for the praise :) - unfortunatly this is "intended". The key combination is executed in the noVNC container - but the back button is an interaction with your browser session and therefore not send to the container. So currently I am not aware of a solution which could catch this and send it to the container.
