### ISSUE TITLE
Pasting

### ISSUE THREAD

**Issue by rosegabe** [powerseb/NoPhish#6]
Users cannot paste their passwords into the noVNC session.

Is there a way to add this functionality? Perhaps with autocusel (https://solveoptimized.com/how-to-copy-paste-text-to-your-server-using-autocutsel/)

**Comment by powerseb** [comment]
Hello,

yes this is unfortunatly expected - noVNC has a clipboard but this works like in guacamole (with a little GUI etc.) and therefore is not suited to the usecase of the used noVNC containers. I see there is currently movement in the development of noVNC to get to work ( https://github.com/novnc/noVNC/pull/1347 ) - so I will keep an eye on that and test the pull request. As soon as I see some postive outcome I will implement it.
