### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by herraristotle** [powerseb/NoPhish#8]
it gave the below error,it wouldn't run.

[+] Configuration file generated
[-] Starting containers
Successfully copied 2.05kB to vnc-user1:/home/headless/user.js
Error response from daemon: No such container: vnc-user1
Error response from daemon: No such container: vnc-user1
Error response from daemon: No such container: vnc-user1
Error response from daemon: No such container: vnc-user1
Successfully copied 2.05kB to vnc-user1:/usr/libexec/noVNCdim/app/images/icons/novnc.ico
Error response from daemon: No such container: vnc-user1
Error response from daemon: No such container: vnc-user1
no such directory
Error response from daemon: No such container: vnc-user1
Error response from daemon: No such container: vnc-user1
Error response from daemon: No such container: vnc-user1
Successfully copied 2.05kB to vnc-user2:/home/headless/user.js
Error response from daemon: No such container: vnc-user2
Error response from daemon: No such container: vnc-user2
Error response from daemon: No such container: vnc-user2
Error response from daemon: No such container: vnc-user2
Successfully copied 2.05kB to vnc-user2:/usr/libexec/noVNCdim/app/images/icons/novnc.ico
Error response from daemon: No such container: vnc-user2
Error response from daemon: No such container: vnc-user2
no such directory
Error response from daemon: No such container: vnc-user2
Error response from daemon: No such container: vnc-user2
Error response from daemon: No such container: vnc-user2
[+] VNC Containers started
[-] Starting reverse proxy
Error response from daemon: container 39c975679d5d8659119f8c975051d0224698e9006970ab0d116a945e2b9dc506 is not running
Error response from daemon: container 39c975679d5d8659119f8c975051d0224698e9006970ab0d116a945e2b9dc506 is not running
Successfully copied 2.05kB to rev-proxy:/var/www/html/favicon.ico
Successfully copied 3.07kB to rev-proxy:/var/www/html/
Successfully copied 3.07kB to rev-proxy:/var/www/html/
Error response from daemon: container 39c975679d5d8659119f8c975051d0224698e9006970ab0d116a945e2b9dc506 is not running
Error response from daemon: container 39c975679d5d8659119f8c975051d0224698e9006970ab0d116a945e2b9dc506 is not running
Error response from daemon: container 39c975679d5d8659119f8c975051d0224698e9006970ab0d116a945e2b9dc506 is not running
Successfully copied 10.8kB to rev-proxy:/var/www/html/
[+] Reverse proxy running
[+] Admin interface available under http://selfhost.ddns.net:65534/status.php
    Login with:
    Username: angler
    Password: QiA2OM1F0wz9h3rL6TYDdQ4Ru9iubxen
[+] Setup completed
[+] Use the following URLs:
http://selfhost.ddns.net/v1/oauth2/authorize?access-token=91d74095-715f-4d36-9ec7-6555d8e4552b
http://selfhost.ddns.net/v2/oauth2/authorize?access-token=0a881159-ce45-4261-bb09-4f1aa1410c46
[-] Starting Loop to collect sessions and cookies from containers
[+] You can check and view the open session by use of the status.php in the output directory
    Every 60 Seconds Cookies and Sessions are exported - Press [CTRL+C] to stop..

**Comment by powerseb** [comment]
Hi, 

regarding your question / problem - first of all i added a minor fix regarding the building process of the containers so use the cleanup function of the script to delete all existing containers - make pull and build them again with the script. Ideally this already fixes the issue.

If not i have seen this error multiple times when the docker enviroment is not properly running maybe due to a incomplete build or if the previous instances were not deleted properly. In both cases my go to solution was to cleanup and rebuild the docker setup with the bash script. I hope this helps if you have any further question please feel free to reach out to me.

**Comment by herraristotle** [comment]
I was able to get the docker up, and running, using ./setup.sh -u 2 -d selfhost.ddns.net -t https://domain.com/login -r true, but i don't see the port opened, accessing with my url shows 404 not found on this server, stopping and restarting apache doesn't fix the error.


![image](https://github.com/user-attachments/assets/b4598fda-98ae-4fcf-ac38-9eae2b3e7beb)

**Comment by powerseb** [comment]
Hi, 

to me it looks like the rev-proxy container is not running which explains why you are not able to reach your target site (or the angler interface) - ideally it should look like this:

![image](https://github.com/user-attachments/assets/859fbae3-2a75-4a5f-864f-3d6857885b03)

Try to run the setup.sh script again and verify afterwards if the rev-proxy container is running - if the container can not be started try a cleanup (manually or by use of the script) and rebuild of the containers. 
 
Further keep in mind that the domain needs to be resolvable (either by use of a public domain you control or manual adjustments of the resolv.conf - for a test setup).

**Comment by herraristotle** [comment]
i am testing on vm, so it should be accessible via my host machine on same network right?

i followed all instructions ot the core, sadly i'm bad with docker.

![image](https://github.com/user-attachments/assets/7fcd06d7-1c61-48ed-8575-5d116c991d00)

![image](https://github.com/user-attachments/assets/62a8549c-304f-412c-a2eb-88aa308be0e7)

**Comment by powerseb** [comment]
Sorry for my late reply because i also currently testing and was running in a simular issue you can try - sudo docker container prune - this should remove all stopped and not running containers after that you can try to start the script with your parameters again.
